"""issues and events

Revision ID: 2f056fc6db10
Revises: 11d96cef31b0
Create Date: 2026-07-27 14:13:03.086587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f056fc6db10'
down_revision: Union[str, Sequence[str], None] = '11d96cef31b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('culprit', sa.String(length=500), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_in_release', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_issues_project_fingerprint')
    )
    op.create_index('ix_issues_project_last_seen', 'issues', ['project_id', 'last_seen_at'], unique=False)
    op.create_index('ix_issues_project_status_last_seen', 'issues', ['project_id', 'status', 'last_seen_at'], unique=False)
    op.create_table('events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('release', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('sdk_name', sa.String(length=64), nullable=True),
    sa.Column('sdk_version', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('exception', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stacktrace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('breadcrumbs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('browser_name', sa.String(length=64), nullable=True),
    sa.Column('browser_version', sa.String(length=32), nullable=True),
    sa.Column('os_name', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_id', name='uq_events_project_event_id')
    )
    op.create_index('ix_events_issue_occurred', 'events', ['issue_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_project_occurred', 'events', ['project_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_project_occurred', table_name='events')
    op.drop_index('ix_events_issue_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_issues_project_status_last_seen', table_name='issues')
    op.drop_index('ix_issues_project_last_seen', table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
