"""logs

Revision ID: 3024305ae8db
Revises: 477985c7392b
Create Date: 2026-07-29 16:50:30.696322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3024305ae8db'
down_revision: Union[str, Sequence[str], None] = '477985c7392b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('span_id', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_id', name='uq_logs_project_event_id')
    )
    op.create_index('ix_logs_project_level_occurred', 'logs', ['project_id', 'level', 'occurred_at'], unique=False)
    op.create_index('ix_logs_project_occurred', 'logs', ['project_id', 'occurred_at'], unique=False)
    op.create_index('ix_logs_trace_id', 'logs', ['trace_id'], unique=False)
    # Expression + jsonb GIN indexes — autogenerate can't detect these.
    op.execute(
        "CREATE INDEX ix_logs_message_fts ON logs "
        "USING GIN (to_tsvector('english', message))"
    )
    op.execute(
        "CREATE INDEX ix_logs_attributes ON logs "
        "USING GIN (attributes jsonb_path_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_logs_attributes")
    op.execute("DROP INDEX IF EXISTS ix_logs_message_fts")
    op.drop_index('ix_logs_trace_id', table_name='logs')
    op.drop_index('ix_logs_project_occurred', table_name='logs')
    op.drop_index('ix_logs_project_level_occurred', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
