"""hosts_and_metrics

Revision ID: 87d5413bf500
Revises: 3024305ae8db
Create Date: 2026-07-29 17:26:04.934012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d5413bf500'
down_revision: Union[str, Sequence[str], None] = '3024305ae8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'hostname', name='uq_hosts_project_hostname')
    )
    op.create_index('ix_hosts_project', 'hosts', ['project_id'], unique=False)
    op.create_table('metrics_1m',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('mem_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mem_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('net_rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('net_tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_1m_host_ts', 'metrics_1m', ['host_id', 'ts'], unique=False)
    # Autogen wanted to drop ix_logs_attributes/ix_logs_message_fts because
    # SQLAlchemy metadata doesn't see raw-SQL GIN indexes. Keep them.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_1m_host_ts', table_name='metrics_1m')
    op.drop_table('metrics_1m')
    op.drop_index('ix_hosts_project', table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
