"""transactions_and_spans

Revision ID: 9140471c5428
Revises: 2f056fc6db10
Create Date: 2026-07-29 13:46:17.924584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9140471c5428'
down_revision: Union[str, Sequence[str], None] = '2f056fc6db10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('op', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('release', sa.String(length=120), nullable=True),
    sa.Column('sdk_name', sa.String(length=64), nullable=True),
    sa.Column('sdk_version', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'transaction_id', name='uq_transactions_project_txn')
    )
    op.create_index('ix_transactions_project_name_started', 'transactions', ['project_id', 'name', 'started_at'], unique=False)
    op.create_index('ix_transactions_project_started', 'transactions', ['project_id', 'started_at'], unique=False)
    op.create_table('spans',
    sa.Column('transaction_pk', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('parent_span_id', sa.String(length=16), nullable=True),
    sa.Column('op', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_pk'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spans_transaction', 'spans', ['transaction_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spans_transaction', table_name='spans')
    op.drop_table('spans')
    op.drop_index('ix_transactions_project_started', table_name='transactions')
    op.drop_index('ix_transactions_project_name_started', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
